export default dummyJourneys = [
    {
      id: 1,
      route: 'BUS-LTW20PD7',
      type: '70-SEATER',
      origin: 'Douala',
      destination: 'Yaounde',
      time: '07:30 AM',
      date: 'Sun, July 21',
      availableSeats: 14,
      totalSeats: 70,
      fare: 'XAF 3000',
    },
    {
      id: 2,
      route: 'TRAIN-XY34RTY',
      type: '300-SEATER',
      origin: 'Bafoussam',
      destination: 'Limbe',
      time: '09:00 AM',
      date: 'Sun, July 21',
      availableSeats: 100,
      totalSeats: 300,
      fare: 'XAF 5000',
    },
    {
      id: 3,
      route: 'BUS-KL56YTH',
      type: '50-SEATER',
      origin: 'Garoua',
      destination: 'Maroua',
      time: '08:30 AM',
      date: 'Sun, July 21',
      availableSeats: 25,
      totalSeats: 50,
      fare: 'XAF 2000',
    },
    {
      id: 4,
      route: 'TRAIN-QP78NBV',
      type: '400-SEATER',
      origin: 'Bamenda',
      destination: 'Buea',
      time: '10:00 AM',
      date: 'Sun, July 21',
      availableSeats: 150,
      totalSeats: 400,
      fare: 'XAF 6000',
    },
    {
      id: 5,
      route: 'BUS-MN45BCX',
      type: '60-SEATER',
      origin: 'Kumba',
      destination: 'Nkongsamba',
      time: '11:00 AM',
      date: 'Sun, July 21',
      availableSeats: 30,
      totalSeats: 60,
      fare: 'XAF 2500',
    },
    {
      id: 6,
      route: 'BUS-LTW20PD7',
      type: '70-SEATER',
      origin: 'Douala',
      destination: 'Yaounde',
      time: '07:30 AM',
      date: 'Sun, July 21',
      availableSeats: 14,
      totalSeats: 70,
      fare: 'XAF 3000',
    },
    {
      id: 7,
      route: 'TRAIN-XY34RTY',
      type: '300-SEATER',
      origin: 'Bafoussam',
      destination: 'Limbe',
      time: '09:00 AM',
      date: 'Sun, July 21',
      availableSeats: 100,
      totalSeats: 300,
      fare: 'XAF 5000',
    },
    {
      id: 8,
      route: 'BUS-KL56YTH',
      type: '50-SEATER',
      origin: 'Garoua',
      destination: 'Maroua',
      time: '08:30 AM',
      date: 'Sun, July 21',
      availableSeats: 25,
      totalSeats: 50,
      fare: 'XAF 2000',
    },
    {
      id: 9,
      route: 'TRAIN-QP78NBV',
      type: '400-SEATER',
      origin: 'Bamenda',
      destination: 'Buea',
      time: '10:00 AM',
      date: 'Sun, July 21',
      availableSeats: 150,
      totalSeats: 400,
      fare: 'XAF 6000',
    },
    {
      id: 10,
      route: 'BUS-MN45BCX',
      type: '60-SEATER',
      origin: 'Kumba',
      destination: 'Nkongsamba',
      time: '11:00 AM',
      date: 'Sun, July 21',
      availableSeats: 30,
      totalSeats: 60,
      fare: 'XAF 4000'
    },
    {
        id: 11,
        route: 'TRAIN-RST90UIO',
        type: '500-SEATER',
        origin: 'Douala',
        destination: 'Kumba',
        time: '01:00 PM',
        date: 'Sun, July 21',
        availableSeats: 250,
        totalSeats: 500,
        fare: 'XAF 7000',
      },
      {
        id: 12,
        route: 'BUS-QWE67PLM',
        type: '80-SEATER',
        origin: 'Yaounde',
        destination: 'Douala',
        time: '02:30 PM',
        date: 'Sun, July 21',
        availableSeats: 50,
        totalSeats: 80,
        fare: 'XAF 3500',
      },
      {
        id: 13,
        route: 'TRAIN-ASD56FGH',
        type: '450-SEATER',
        origin: 'Bafoussam',
        destination: 'Buea',
        time: '03:00 PM',
        date: 'Sun, July 21',
        availableSeats: 200,
        totalSeats: 450,
        fare: 'XAF 5500',
      },
      {
        id: 14,
        route: 'BUS-POI78JKL',
        type: '90-SEATER',
        origin: 'Nkongsamba',
        destination: 'Yaounde',
        time: '04:00 PM',
        date: 'Sun, July 21',
        availableSeats: 70,
        totalSeats: 90,
        fare: 'XAF 4000',
      },
      {
        id: 15,
        route: 'TRAIN-ZXC90VBN',
        type: '350-SEATER',
        origin: 'Maroua',
        destination: 'Douala',
        time: '05:30 PM',
        date: 'Sun, July 21',
        availableSeats: 150,
        totalSeats: 350,
        fare: 'XAF 6500',
      },
      {
        id: 16,
        route: 'BUS-BNM67GHJ',
        type: '70-SEATER',
        origin: 'Buea',
        destination: 'Kumba',
        time: '06:00 PM',
        date: 'Sun, July 21',
        availableSeats: 35,
        totalSeats: 70,
        fare: 'XAF 3000',
      },
      {
        id: 17,
        route: 'TRAIN-PLM34QWE',
        type: '400-SEATER',
        origin: 'Douala',
        destination: 'Bafoussam',
        time: '07:00 PM',
        date: 'Sun, July 21',
        availableSeats: 180,
        totalSeats: 400,
        fare: 'XAF 6000',
      },
      {
        id: 18,
        route: 'BUS-OKL90NMJ',
        type: '60-SEATER',
        origin: 'Yaounde',
        destination: 'Garoua',
        time: '08:00 PM',
        date: 'Sun, July 21',
        availableSeats: 40,
        totalSeats: 60,
        fare: 'XAF 5000',
      },
      {
        id: 19,
        route: 'TRAIN-IUJ78MNB',
        type: '500-SEATER',
        origin: 'Kumba',
        destination: 'Yaounde',
        time: '09:30 PM',
        date: 'Sun, July 21',
        availableSeats: 300,
        totalSeats: 500,
        fare: 'XAF 8000',
      },
      {
        id: 20,
        route: 'BUS-QAZ12WSX',
        type: '80-SEATER',
        origin: 'Limbe',
        destination: 'Bamenda',
        time: '10:00 PM',
        date: 'Sun, July 21',
        availableSeats: 60,
        totalSeats: 80,
        fare: 'XAF 4000',
      },
      {
        id: 21,
        route: 'TRAIN-EDC34RFV',
        type: '300-SEATER',
        origin: 'Nkongsamba',
        destination: 'Douala',
        time: '11:00 PM',
        date: 'Sun, July 21',
        availableSeats: 200,
        totalSeats: 300,
        fare: 'XAF 6000',
      },
      {
        id: 22,
        route: 'BUS-TGB12YHN',
        type: '100-SEATER',
        origin: 'Bafoussam',
        destination: 'Yaounde',
        time: '12:00 AM',
        date: 'Sun, July 21',
        availableSeats: 80,
        totalSeats: 100,
        fare: 'XAF 5000',
      },
      {
        id: 23,
        route: 'TRAIN-BGV67HJH',
        type: '450-SEATER',
        origin: 'Maroua',
        destination: 'Garoua',
        time: '01:00 AM',
        date: 'Sun, July 21',
        availableSeats: 250,
        totalSeats: 450,
        fare: 'XAF 7000',
      },
      {
        id: 24,
        route: 'BUS-QWE45EDC',
        type: '70-SEATER',
        origin: 'Buea',
        destination: 'Nkongsamba',
        time: '02:30 AM',
        date: 'Sun, July 21',
        availableSeats: 50,
        totalSeats: 70,
        fare: 'XAF 3500',
      },
      {
        id: 25,
        route: 'TRAIN-MNB45YUH',
        type: '400-SEATER',
        origin: 'Yaounde',
        destination: 'Douala',
        time: '03:00 AM',
        date: 'Sun, July 21',
        availableSeats: 200,
        totalSeats: 400,
        fare: 'XAF 5500',
      },
      {
        id: 26,
        route: 'BUS-IKL12OJU',
        type: '90-SEATER',
        origin: 'Douala',
        destination: 'Kumba',
        time: '04:00 AM',
        date: 'Sun, July 21',
        availableSeats: 70,
        totalSeats: 90,
        fare: 'XAF 4000',
      },
      {
        id: 27,
        route: 'TRAIN-PLM78QAZ',
        type: '350-SEATER',
        origin: 'Garoua',
        destination: 'Bamenda',
        time: '05:30 AM',
        date: 'Sun, July 21',
        availableSeats: 150,
        totalSeats: 350,
        fare: 'XAF 6500',
      },
      {
        id: 28,
        route: 'BUS-ZXW67EDC',
        type: '60-SEATER',
        origin: 'Nkongsamba',
        destination: 'Limbe',
        time: '06:00 AM',
        date: 'Sun, July 21',
        availableSeats: 35,
        totalSeats: 60,
        fare: 'XAF 3000',
      },
      {
        id: 29,
        route: 'TRAIN-YHJ34LOP',
        type: '400-SEATER',
        origin: 'Douala',
        destination: 'Yaounde',
        time: '07:00 AM',
        date: 'Sun, July 21',
        availableSeats: 180,
        totalSeats: 400,
        fare: 'XAF 6000',
      },
      {
        id: 30,
        route: 'BUS-UIK12JNM',
        type: '80-SEATER',
        origin: 'Bamenda',
        destination: 'Kumba',
        time: '08:00 AM',
        date: 'Sun, July 21',
        availableSeats: 50,
        totalSeats: 80,
        fare: 'XAF 3500',
      },
    ];
    
// export default dummyJourneys;