export default dummyTickets = [
  {
    id: 1,
    route: "BUS-LTW20PD7",
    type: "70-SEATER",
    origin: "Douala",
    destination: "Yaounde",
    time: "07:30 AM",
    date: "Sun, July 21",
    fare: "XAF 3000",
    status: "used",
    position: 1,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 2,
    route: "TRAIN-XY34RTY",
    type: "300-SEATER",
    origin: "Bafoussam",
    destination: "Limbe",
    time: "09:00 AM",
    date: "Sun, July 21",
    fare: "XAF 5000",
    status: "new",
    position: 2,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 3,
    route: "BUS-KL56YTH",
    type: "50-SEATER",
    origin: "Garoua",
    destination: "Maroua",
    time: "08:30 AM",
    date: "Sun, July 21",
    fare: "XAF 2000",
    status: "used",
    position: 3,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 4,
    route: "TRAIN-QP78NBV",
    type: "400-SEATER",
    origin: "Bamenda",
    destination: "Buea",
    time: "10:00 AM",
    date: "Sun, July 21",
    fare: "XAF 6000",
    status: "new",
    position: 4,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 5,
    route: "BUS-MN45BCX",
    type: "60-SEATER",
    origin: "Kumba",
    destination: "Nkongsamba",
    time: "11:00 AM",
    date: "Sun, July 21",
    fare: "XAF 2500",
    status: "used",
    position: 5,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 6,
    route: "BUS-LTW20PD7",
    type: "70-SEATER",
    origin: "Douala",
    destination: "Yaounde",
    time: "07:30 AM",
    date: "Sun, July 21",
    fare: "XAF 3000",
    status: "new",
    position: 6,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 7,
    route: "TRAIN-XY34RTY",
    type: "300-SEATER",
    origin: "Bafoussam",
    destination: "Limbe",
    time: "09:00 AM",
    date: "Sun, July 21",
    fare: "XAF 5000",
    status: "used",
    position: 7,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 8,
    route: "BUS-KL56YTH",
    type: "50-SEATER",
    origin: "Garoua",
    destination: "Maroua",
    time: "08:30 AM",
    date: "Sun, July 21",
    fare: "XAF 2000",
    status: "new",
    position: 8,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 9,
    route: "TRAIN-QP78NBV",
    type: "400-SEATER",
    origin: "Bamenda",
    destination: "Buea",
    time: "10:00 AM",
    date: "Sun, July 21",
    fare: "XAF 6000",
    status: "used",
    position: 9,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 10,
    route: "BUS-MN45BCX",
    type: "60-SEATER",
    origin: "Kumba",
    destination: "Nkongsamba",
    time: "11:00 AM",
    date: "Sun, July 21",
    fare: "XAF 4000",
    status: "new",
    position: 10,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 11,
    route: "TRAIN-RST90UIO",
    type: "500-SEATER",
    origin: "Douala",
    destination: "Kumba",
    time: "01:00 PM",
    date: "Sun, July 21",
    fare: "XAF 7000",
    status: "used",
    position: 11,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 12,
    route: "BUS-QWE67PLM",
    type: "80-SEATER",
    origin: "Yaounde",
    destination: "Douala",
    time: "02:30 PM",
    date: "Sun, July 21",
    fare: "XAF 3500",
    status: "new",
    position: 12,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 13,
    route: "TRAIN-ASD56FGH",
    type: "450-SEATER",
    origin: "Bafoussam",
    destination: "Buea",
    time: "03:00 PM",
    date: "Sun, July 21",
    fare: "XAF 5500",
    status: "used",
    position: 13,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 14,
    route: "BUS-POI78JKL",
    type: "90-SEATER",
    origin: "Nkongsamba",
    destination: "Yaounde",
    time: "04:00 PM",
    date: "Sun, July 21",
    fare: "XAF 4000",
    status: "new",
    position: 14,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 15,
    route: "TRAIN-ZXC90VBN",
    type: "350-SEATER",
    origin: "Maroua",
    destination: "Douala",
    time: "05:30 PM",
    date: "Sun, July 21",
    fare: "XAF 6500",
    status: "used",
    position: 15,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 16,
    route: "BUS-BNM67GHJ",
    type: "70-SEATER",
    origin: "Buea",
    destination: "Kumba",
    time: "06:00 PM",
    date: "Sun, July 21",
    fare: "XAF 3000",
    status: "new",
    position: 16,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 17,
    route: "TRAIN-PLM34QWE",
    type: "400-SEATER",
    origin: "Douala",
    destination: "Bafoussam",
    time: "07:00 PM",
    date: "Sun, July 21",
    fare: "XAF 6000",
    status: "used",
    position: 17,
    userName: "Mosongo Adina", // New attribute
    userType: "Passenger", // New attribute
  },
  {
    id: 18,
    route: "BUS-OKL90NMJ",
    type: "60-SEATER",
    origin: "Yaounde",
    destination: "Garoua",
    time: "08:00 PM",
    date: "Sun, July 21",
    fare: "XAF 5000",
    status: "new",
    position: 18,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 19,
    route: "TRAIN-IUJ78MNB",
    type: "500-SEATER",
    origin: "Kumba",
    destination: "Yaounde",
    time: "09:30 PM",
    date: "Sun, July 21",
    fare: "XAF 8000",
    status: "used",
    position: 19,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 20,
    route: "BUS-QAZ12WSX",
    type: "80-SEATER",
    origin: "Limbe",
    destination: "Bamenda",
    time: "10:00 PM",
    date: "Sun, July 21",
    fare: "XAF 4000",
    status: "new",
    position: 20,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 21,
    route: "TRAIN-EDC34RFV",
    type: "300-SEATER",
    origin: "Nkongsamba",
    destination: "Douala",
    time: "11:00 PM",
    date: "Sun, July 21",
    fare: "XAF 6000",
    status: "used",
    position: 21,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 22,
    route: "BUS-TGB12YHN",
    type: "100-SEATER",
    origin: "Bafoussam",
    destination: "Yaounde",
    time: "12:00 AM",
    date: "Sun, July 21",
    fare: "XAF 5000",
    status: "new",
    position: 22,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 23,
    route: "TRAIN-BGV67HJH",
    type: "450-SEATER",
    origin: "Maroua",
    destination: "Garoua",
    time: "01:00 AM",
    date: "Sun, July 21",
    fare: "XAF 7000",
    status: "used",
    position: 23,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 24,
    route: "BUS-QWE45EDC",
    type: "70-SEATER",
    origin: "Buea",
    destination: "Nkongsamba",
    time: "02:30 AM",
    date: "Sun, July 21",
    fare: "XAF 3500",
    status: "new",
    position: 24,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 25,
    route: "TRAIN-LKI87UYT",
    type: "300-SEATER",
    origin: "Limbe",
    destination: "Douala",
    time: "03:00 AM",
    date: "Sun, July 21",
    fare: "XAF 6000",
    status: "used",
    position: 25,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 26,
    route: "BUS-QAZ34WSX",
    type: "90-SEATER",
    origin: "Garoua",
    destination: "Yaounde",
    time: "04:00 AM",
    date: "Sun, July 21",
    fare: "XAF 4000",
    status: "new",
    position: 26,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 27,
    route: "TRAIN-ERT56YUI",
    type: "450-SEATER",
    origin: "Bafoussam",
    destination: "Douala",
    time: "05:30 AM",
    date: "Sun, July 21",
    fare: "XAF 7000",
    status: "used",
    position: 27,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 28,
    route: "BUS-NMK78HJK",
    type: "60-SEATER",
    origin: "Kumba",
    destination: "Buea",
    time: "06:00 AM",
    date: "Sun, July 21",
    fare: "XAF 3000",
    status: "new",
    position: 28,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 29,
    route: "TRAIN-UIO12POI",
    type: "400-SEATER",
    origin: "Douala",
    destination: "Bafoussam",
    time: "07:30 AM",
    date: "Sun, July 21",
    fare: "XAF 6000",
    status: "used",
    position: 29,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 30,
    route: "BUS-HGJ89IUY",
    type: "80-SEATER",
    origin: "Yaounde",
    destination: "Kumba",
    time: "08:30 AM",
    date: "Sun, July 21",
    fare: "XAF 4000",
    status: "new",
    position: 30,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 31,
    route: "TRAIN-YUH56RTY",
    type: "500-SEATER",
    origin: "Limbe",
    destination: "Bamenda",
    time: "09:00 AM",
    date: "Sun, July 21",
    fare: "XAF 8000",
    status: "used",
    position: 31,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 32,
    route: "BUS-WRT23TYU",
    type: "70-SEATER",
    origin: "Buea",
    destination: "Douala",
    time: "10:00 AM",
    date: "Sun, July 21",
    fare: "XAF 3500",
    status: "new",
    position: 32,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 33,
    route: "TRAIN-IKL34BNM",
    type: "300-SEATER",
    origin: "Yaounde",
    destination: "Bafoussam",
    time: "11:00 AM",
    date: "Sun, July 21",
    fare: "XAF 6000",
    status: "used",
    position: 33,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 34,
    route: "BUS-OLP67RTY",
    type: "100-SEATER",
    origin: "Nkongsamba",
    destination: "Garoua",
    time: "12:00 PM",
    date: "Mon, July 22",
    fare: "XAF 5000",
    status: "new",
    position: 34,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 35,
    route: "TRAIN-KLM56YHN",
    type: "350-SEATER",
    origin: "Douala",
    destination: "Maroua",
    time: "01:30 PM",
    date: "Mon, July 22",
    fare: "XAF 6500",
    status: "used",
    position: 35,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 36,
    route: "BUS-ZXC12RTY",
    type: "60-SEATER",
    origin: "Bafoussam",
    destination: "Yaounde",
    time: "02:00 PM",
    date: "Mon, July 22",
    fare: "XAF 3000",
    status: "new",
    position: 36,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 37,
    route: "TRAIN-POI78VBN",
    type: "400-SEATER",
    origin: "Garoua",
    destination: "Douala",
    time: "03:00 PM",
    date: "Mon, July 22",
    fare: "XAF 6000",
    status: "used",
    position: 37,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 38,
    route: "BUS-HJK45TGB",
    type: "70-SEATER",
    origin: "Limbe",
    destination: "Nkongsamba",
    time: "04:00 PM",
    date: "Mon, July 22",
    fare: "XAF 3500",
    status: "new",
    position: 38,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 39,
    route: "TRAIN-MNB90QAZ",
    type: "450-SEATER",
    origin: "Buea",
    destination: "Kumba",
    time: "05:30 PM",
    date: "Mon, July 22",
    fare: "XAF 7000",
    status: "used",
    position: 39,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 40,
    route: "BUS-UIO34YHN",
    type: "90-SEATER",
    origin: "Maroua",
    destination: "Yaounde",
    time: "06:00 PM",
    date: "Mon, July 22",
    fare: "XAF 4000",
    status: "new",
    position: 40,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 41,
    route: "TRAIN-PLK23WRT",
    type: "500-SEATER",
    origin: "Douala",
    destination: "Bamenda",
    time: "07:00 PM",
    date: "Mon, July 22",
    fare: "XAF 8000",
    status: "used",
    position: 41,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 42,
    route: "BUS-ERT12QWE",
    type: "80-SEATER",
    origin: "Yaounde",
    destination: "Limbe",
    time: "08:00 PM",
    date: "Mon, July 22",
    fare: "XAF 4000",
    status: "new",
    position: 42,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 43,
    route: "TRAIN-RFV90EDC",
    type: "300-SEATER",
    origin: "Nkongsamba",
    destination: "Douala",
    time: "09:30 PM",
    date: "Mon, July 22",
    fare: "XAF 6000",
    status: "used",
    position: 43,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 44,
    route: "BUS-YHN78UIO",
    type: "100-SEATER",
    origin: "Bafoussam",
    destination: "Garoua",
    time: "10:00 PM",
    date: "Mon, July 22",
    fare: "XAF 5000",
    status: "new",
    position: 44,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 45,
    route: "TRAIN-PLM23BVC",
    type: "450-SEATER",
    origin: "Kumba",
    destination: "Yaounde",
    time: "11:00 PM",
    date: "Mon, July 22",
    fare: "XAF 7000",
    status: "used",
    position: 45,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 46,
    route: "BUS-WSX90RTY",
    type: "70-SEATER",
    origin: "Limbe",
    destination: "Douala",
    time: "12:00 AM",
    date: "Mon, July 22",
    fare: "XAF 3500",
    status: "new",
    position: 46,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 47,
    route: "TRAIN-HJK45BNM",
    type: "400-SEATER",
    origin: "Garoua",
    destination: "Bafoussam",
    time: "01:30 AM",
    date: "Mon, July 22",
    fare: "XAF 6000",
    status: "used",
    position: 47,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 48,
    route: "BUS-ERT67YHN",
    type: "90-SEATER",
    origin: "Buea",
    destination: "Nkongsamba",
    time: "02:00 AM",
    date: "Mon, July 22",
    fare: "XAF 4000",
    status: "new",
    position: 48,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 49,
    route: "TRAIN-YUI12ERT",
    type: "350-SEATER",
    origin: "Douala",
    destination: "Maroua",
    time: "03:00 AM",
    date: "Mon, July 22",
    fare: "XAF 6500",
    status: "used",
    position: 49,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 50,
    route: "BUS-QAZ90EDC",
    type: "60-SEATER",
    origin: "Yaounde",
    destination: "Bafoussam",
    time: "04:30 AM",
    date: "Mon, July 22",
    fare: "XAF 3000",
    status: "new",
    position: 50,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 51,
    route: "TRAIN-TGB45QWE",
    type: "500-SEATER",
    origin: "Kumba",
    destination: "Yaounde",
    time: "05:30 AM",
    date: "Mon, July 22",
    fare: "XAF 8000",
    status: "used",
    position: 51,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 52,
    route: "BUS-EDC12RFV",
    type: "80-SEATER",
    origin: "Limbe",
    destination: "Douala",
    time: "06:00 AM",
    date: "Mon, July 22",
    fare: "XAF 4000",
    status: "new",
    position: 52,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
  {
    id: 53,
    route: "TRAIN-YHN67UIO",
    type: "400-SEATER",
    origin: "Nkongsamba",
    destination: "Bamenda",
    time: "07:30 AM",
    date: "Mon, July 22",
    fare: "XAF 6000",
    status: "used",
    position: 53,
    userName: "Mosongo Adina",
    userType: "Passenger",
  },
];
